# Generated by Django 3.0.11 on 2021-02-19 03:47

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image_formats', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('insertion_date', models.DateField(auto_now_add=True)),
                ('project_id', models.CharField(default='', max_length=10000)),
                ('date_acquisition', models.DateField(auto_now_add=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_service.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSampling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='')),
                ('insertion_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageMetaData',
            fields=[
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='image_service.Image')),
                ('has_tb', models.BooleanField()),
                ('original_report', models.TextField(null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('date_exam', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(verbose_name='Date of CXR evaluation')),
                ('image_quality', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='CXR with minimal criteria for interpretation?')),
                ('reason_low_quality', models.CharField(blank=True, choices=[('PoorIns', 'Poor inspiration'), ('UnderPen', 'Under-penetrated'), ('OverPen', 'Over-penetrated'), ('CropCost', 'Costophrenic are cropped'), ('CropApices', 'Apices are cropped'), ('Art', 'Artifacts jeopardizing interpretation'), ('Rotated', 'Rotated')], max_length=10, null=True, verbose_name='Why?')),
                ('report_version', models.PositiveSmallIntegerField(verbose_name='Report version')),
                ('report_content', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Report content')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image_service.Image', verbose_name='X-Ray image')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Radiologist ID')),
            ],
        ),
    ]
