# Generated by Django 3.0.10 on 2020-11-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, unique=True)),
                ('image_formats', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image_service/image/')),
                ('has_tb', models.BooleanField()),
                ('original_report', models.CharField(max_length=10000, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_service.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.URLField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_service.DataSet')),
            ],
        ),
    ]
