# Generated by Django 3.0.10 on 2020-11-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='imagemetadata',
            name='dataset',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='static/image_service/image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_service.Image'),
        ),
    ]
