# Generated by Django 3.1.5 on 2021-03-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, null=True),
        ),
    ]
