# Generated by Django 3.0.10 on 2020-11-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='project_id',
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='image_formats',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
