# Generated by Django 3.1.8 on 2021-08-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0002_auto_20210528_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='has_tb',
            field=models.BooleanField(null=True),
        ),
    ]
