# Generated by Django 3.0.11 on 2020-11-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0002_auto_20201122_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='exam_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='insertion_date',
            field=models.DateField(auto_now=True),
        ),
    ]
