# Generated by Django 3.0.10 on 2020-11-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0002_auto_20201104_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='image_service.Image'),
        ),
    ]
