# Generated by Django 3.1.8 on 2021-12-10 03:07

from django.db import migrations, models
import image_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0003_auto_20210818_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=image_service.models.get_upload_path),
        ),
    ]
