# Generated by Django 3.0.11 on 2020-11-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0003_auto_20201123_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='exam_date',
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='date_exam',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='insertion_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
