# Generated by Django 3.1 on 2020-09-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0003_auto_20200924_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='database',
            field=models.CharField(max_length=50, verbose_name='Data base name'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='image_formats',
            field=models.ManyToManyField(to='image_service.Formats', verbose_name='list of formats'),
        ),
    ]
