# Generated by Django 3.0.10 on 2020-11-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0003_auto_20201104_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemetadata',
            name='id',
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='image_service.Image'),
        ),
    ]
