# Generated by Django 3.0.10 on 2020-11-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0004_auto_20201104_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='image_service.Image'),
        ),
    ]
