# Generated by Django 3.1.8 on 2022-06-24 21:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0004_auto_20211210_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=10)),
                ('fold', models.CharField(max_length=10)),
                ('partitions', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='additional_information',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='synthetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='folds',
            constraint=models.UniqueConstraint(fields=('folder', 'fold'), name='folder_fold'),
        ),
    ]
