# Generated by Django 3.0.11 on 2020-11-23 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_service', '0004_auto_20201123_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_insertion_date', models.DateTimeField(auto_now_add=True, verbose_name='Reported on')),
                ('report', models.TextField()),
                ('form_version', models.TextField()),
                ('image_quality', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Is image quality satisfactory?')),
                ('reason_low_quality', models.CharField(blank=True, choices=[('PoorIns', 'Poor inspiration'), ('UnderPen', 'Under-penetrated'), ('OverPen', 'Over-penetrated'), ('CropCost', 'Costophrenic angles are cropped'), ('CropApices', 'Apices are cropped'), ('Art', 'Artefacts')], max_length=10, null=True, verbose_name='Reason for low quality')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Report generated by')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image_service.Image')),
            ],
        ),
    ]
