# Generated by Django 3.0.11 on 2020-11-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='project_id',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
