# Generated by Django 3.1.8 on 2022-07-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0005_auto_20220624_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossValidationCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.CharField(max_length=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_service.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='CrossValidationFold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fold_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CrossValidationFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=30)),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_service.crossvalidationcluster')),
            ],
        ),
        migrations.CreateModel(
            name='CrossValidationFoldimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.BooleanField(default=False)),
                ('test', models.BooleanField(default=False)),
                ('validation', models.BooleanField(default=False)),
                ('fold_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_service.crossvalidationfold')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_service.image')),
            ],
        ),
        migrations.DeleteModel(
            name='Folds',
        ),
        migrations.AddField(
            model_name='crossvalidationfold',
            name='folder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_service.crossvalidationfolder'),
        ),
        migrations.AddConstraint(
            model_name='crossvalidationfoldimages',
            constraint=models.UniqueConstraint(fields=('project_id', 'fold_id'), name='cross_validation_fold_image_unique'),
        ),
        migrations.AddConstraint(
            model_name='crossvalidationfolder',
            constraint=models.UniqueConstraint(fields=('cluster_id', 'folder_id'), name='cross_validation_folder_unique'),
        ),
        migrations.AddConstraint(
            model_name='crossvalidationfold',
            constraint=models.UniqueConstraint(fields=('fold_id',), name='cross_validation_fold_unique'),
        ),
        migrations.AddConstraint(
            model_name='crossvalidationcluster',
            constraint=models.UniqueConstraint(fields=('cluster_id',), name='cross_validation_cluster_unique'),
        ),
    ]
