# Generated by Django 3.1.8 on 2022-07-05 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0005_auto_20220624_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossValidationCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.CharField(max_length=20, unique=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_service.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='CrossValidationFold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fold_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrossValidationFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=30, unique=True)),
                ('cluster_id', models.ForeignKey(db_column='cluster_id', on_delete=django.db.models.deletion.CASCADE, to='image_service.crossvalidationcluster', to_field='cluster_id')),
            ],
        ),
        migrations.CreateModel(
            name='CrossValidationFoldimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.BooleanField(default=False)),
                ('test', models.BooleanField(default=False)),
                ('validation', models.BooleanField(default=False)),
                ('fold_id', models.ForeignKey(db_column='fold_id', on_delete=django.db.models.deletion.CASCADE, to='image_service.crossvalidationfold', to_field='fold_id')),
            ],
        ),
        migrations.DeleteModel(
            name='Folds',
        ),
        migrations.AlterField(
            model_name='image',
            name='project_id',
            field=models.CharField(max_length=10000, unique=True),
        ),
        migrations.AddField(
            model_name='crossvalidationfoldimages',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='image_service.image', to_field='project_id'),
        ),
        migrations.AddField(
            model_name='crossvalidationfold',
            name='folder_id',
            field=models.ForeignKey(db_column='folder_id', on_delete=django.db.models.deletion.CASCADE, to='image_service.crossvalidationfolder', to_field='folder_id'),
        ),
        migrations.AddConstraint(
            model_name='crossvalidationfoldimages',
            constraint=models.UniqueConstraint(fields=('project_id', 'fold_id'), name='cross_validation_fold_image_unique'),
        ),
    ]
