# Generated by Django 3.1.8 on 2022-07-06 02:33

from django.db import migrations, models
import image_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0006_auto_20220704_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossvalidationcluster',
            name='file',
            field=models.FileField(default=None, upload_to=image_service.models.get_upload_path),
        ),
    ]
