# Generated by Django 3.0.11 on 2020-11-24 21:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0006_image_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='form_version',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
