# Generated by Django 4.0.6 on 2022-08-11 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0007_crossvalidationcluster_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossvalidationcluster',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crossvalidationfold',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crossvalidationfolder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crossvalidationfoldimages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagemetadata',
            name='additional_information',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='imagesampling',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_content',
            field=models.JSONField(verbose_name='Report content'),
        ),
        migrations.CreateModel(
            name='DataQualityAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_penetrated', models.BooleanField(null=True)),
                ('over_penetrated', models.BooleanField(null=True)),
                ('costophrenic_cropped', models.BooleanField(null=True)),
                ('apices_cropped', models.BooleanField(null=True)),
                ('insertion_date', models.DateField(auto_now_add=True)),
                ('reliable_radiography', models.BooleanField(null=True)),
                ('minimum_interpretation_quality', models.BooleanField(null=True)),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='image_service.image')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dataqualityannotation',
            constraint=models.UniqueConstraint(fields=('project_id',), name='data_quality_annotation_unique'),
        ),
    ]
