# Generated by Django 3.1 on 2020-09-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0007_auto_20200927_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formats', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['formats'],
            },
        ),
        migrations.AlterField(
            model_name='dataset',
            name='image_formats',
            field=models.ManyToManyField(to='image_service.Formats', verbose_name='list of formats'),
        ),
    ]
