# Generated by Django 3.2 on 2022-08-22 21:50

from django.db import migrations, models
import django.db.models.deletion
import image_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0008_alter_crossvalidationcluster_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image_service.models.get_upload_path)),
                ('insertion_date', models.DateField(auto_now_add=True)),
                ('project_id', models.CharField(max_length=10000, unique=True)),
                ('date_acquisition', models.DateField(auto_now_add=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_service.dataset')),
            ],
        ),
        migrations.AlterField(
            model_name='crossvalidationcluster',
            name='file',
            field=models.FileField(default=None, upload_to=image_service.models.get_cluster_upload_path),
        ),
        migrations.AlterField(
            model_name='dataqualityannotation',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='image_service.image', to_field='project_id'),
        ),
        migrations.CreateModel(
            name='ImageMetaDataValidation',
            fields=[
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='image_service.imagevalidation')),
                ('has_tb', models.BooleanField(null=True)),
                ('original_report', models.TextField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('date_exam', models.DateField(blank=True, null=True)),
                ('synthetic', models.BooleanField(default=False)),
                ('additional_information', models.JSONField(null=True)),
            ],
        ),
    ]
