# Generated by Django 3.2 on 2023-03-21 02:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import image_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0009_auto_20220822_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetCrossValidationFolds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=image_service.models.get_cluster_upload_path)),
                ('file_type', models.CharField(choices=[('pkl', 'Pickle'), ('csv', 'CSV')], max_length=3, null=True)),
                ('updated_at', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='crossvalidationfolder',
            name='cluster_id',
        ),
        migrations.RemoveField(
            model_name='crossvalidationfoldimages',
            name='fold_id',
        ),
        migrations.RemoveField(
            model_name='crossvalidationfoldimages',
            name='project_id',
        ),
        migrations.AddField(
            model_name='dataset',
            name='absolute_path_location',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='current_state_hash',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='last_update',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='dataset',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='synthetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='image_hash',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=500, upload_to=image_service.models.get_upload_path),
        ),
        migrations.DeleteModel(
            name='CrossValidationFold',
        ),
        migrations.DeleteModel(
            name='CrossValidationFolder',
        ),
        migrations.DeleteModel(
            name='CrossValidationFoldimages',
        ),
        migrations.AddField(
            model_name='datasetcrossvalidationfolds',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_service.dataset'),
        ),
        migrations.AddConstraint(
            model_name='datasetcrossvalidationfolds',
            constraint=models.UniqueConstraint(fields=('dataset',), name='cross_validation_folds_dataset_id_unique'),
        ),
    ]
