# Generated by Django 3.1 on 2020-10-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0009_auto_20201002_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
