# Generated by Django 3.1 on 2020-10-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0010_createuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='idd',
        ),
        migrations.AlterField(
            model_name='createuser',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
