# Generated by Django 3.1 on 2020-10-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0011_auto_20201006_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUser',
        ),
    ]
