# Generated by Django 3.1 on 2020-10-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0013_remove_dataset_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='database',
            field=models.CharField(max_length=50, unique=True, verbose_name='Data base name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
