# Generated by Django 3.1 on 2020-10-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0014_auto_20201013_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.CharField(max_length=50),
        ),
    ]
