# Generated by Django 3.1 on 2020-10-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0015_auto_20201013_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='original_report',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
