# Generated by Django 3.1 on 2020-10-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_service', '0016_auto_20201014_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='database',
            new_name='name',
        ),
    ]
