version: '3.8'
services:
  db:
    image: postgres:13.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=R2E)5Dqd5ixizrU>+[mR
    volumes:
        - PostgresDB:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  dorothy-image:
    image: tbbrics/dorothy-image-service-web:latest
    command: ./run_server.sh
    volumes:
      - ./imagesrep:/imagesrep
    depends_on:
      - db
    ports:
      - "80:8000"
    environment:
      DEBUG: 'true'
    restart: on-failure
  notebook:
    image: tbbrics/dorothy-image-service-web:latest
    command: python manage.py shell_plus --notebook
    volumes:
      - ./imagesrep:/imagesrep
    depends_on:
      - dorothy-image
    ports:
      - "8888:8888"
    environment:
      DEBUG: 'true'
    restart: on-failure
#  mlflow:
#    image: patrickfbraz/dorothy-mlflow-service:0.1.3
#    command: ./run_mlflow.sh
#    ports:
#      - "5000:80"
#  nginx:
#    image: tbbrics/dorothy-image-service-web:latest
#    command: ./server/run_nginx.sh
#    depends_on:
#      - mlflow
#      - dorothy-image
#    ports:
#      - "80:80"
#      - "443:443"
volumes:
    PostgresDB:
    ImagesRep: