version: '3.8'

services:
  db:
    image: postgres:13.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=R2E)5Dqd5ixizrU>+[mR
    volumes:
        - PostgresDB:/var/lib/postgresql/data
  web:
    ports:
      - "80:80"
    environment:
        PRODUCTION: 'true'
    image: tbbrics/dorothy-image-service-web:production
    command: ./run_server.sh
    volumes:
      - ImagesRep:/imagesrep
    depends_on:
      - db

volumes:
    PostgresDB:
    ImagesRep:
