version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=R2E)5Dqd5ixizrU>+[mR
    volumes:
        - PostgresDB:/var/lib/postgresql/data
  web:
    image: luccascarpa/dorothy-image-service-web
    command: ./run_server.sh
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ImagesRep:/imagesrep
    depends_on:
      - db

volumes:
    PostgresDB:
    ImagesRep:
