# Generated by Django 3.1 on 2020-09-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200927_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formats',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='image_formats',
            field=models.ManyToManyField(related_name='_dataset_image_formats_+', to='core.DataSet'),
        ),
    ]
