# Generated by Django 3.1 on 2020-10-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200927_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='image_formats',
        ),
        migrations.AddField(
            model_name='dataset',
            name='image_formats',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Formats',
        ),
    ]
