# Generated by Django 3.1 on 2020-09-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200927_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formats',
            options={'ordering': ['formats']},
        ),
        migrations.AddField(
            model_name='formats',
            name='formats',
            field=models.CharField(default='png', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='image_formats',
            field=models.ManyToManyField(to='core.Formats'),
        ),
    ]
