# Generated by Django 3.1 on 2020-09-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200927_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='image_formats',
            field=models.ManyToManyField(to='core.Formats', verbose_name='list of formats'),
        ),
    ]
